name: Maester Daily Tests

on:
  push:
    branches: ["main"]
  # Run once a day at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      checks: write

jobs:
  run-maester-tests:
    name: Run Maester Tests
    runs-on: ubuntu-latest
    steps:
    - name: Run Maester 🔥
      uses: maester365/maester-action@v1.0.1 # to this line
      with:
        # your parameters here
        include_private_tests: true # this will checkout the current repository and was the default behavior of the old action
        # if you used install_prerelease: true you should add this line and remove the old one
        maester_version: preview # pick the exact version of the Maester module you want to use or 'latest' or 'preview'
        client_id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        pester_verbosity: Detailed
        mail_recipients: cloudadmin@c4a8korriban.onmicrosoft.com
        mail_userid: bc7b9710-54c2-4112-9b2e-cbf8bbb50b23
